[aws]
disabled = true

[git_branch]
symbol = "🌱 "

[username]
show_always = true

[battery]
charging_symbol = "⚡️"

[directory]
truncate_to_repo = false

[hostname]
ssh_only = false

[golang]
symbol = " "
